version: "3"
services:

  webserver:
    image: nginx
    environment:
      - NGINX_SERVER_NAME
    volumes:
      - ./web/templates:/etc/nginx/templates
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    image: gustavoaborges/ifa-br-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/IFABR
      ADDONS: "@eeacms/volto-listing-block"
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: gustavoaborges/ifa-br-backend:latest
    environment:
      SITE: IFABR
      ZEO_ADDRESS: db:8100
    ports:
    - "8080:8080"
    depends_on:
      - db

  db:
    image: plone/plone-zeo:latest
    restart: always
    volumes:
      - data:/data
    ports:
    - "8100:8100"

volumes:
  data: {}