version: "3"
services:

  webserver:
    image: nginx
    environment:
      - NGINX_SERVER_NAME
    volumes:
      - ./web/templates:/etc/nginx/templates
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"
    - "443:443"
    restart: always
    networks:
      - web
      - services

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  frontend:
    image: gustavoaborges/ifa-br-frontend:latest
    # build: frontend/.
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/IFABR
    ports:
    - "3000:3000"
    depends_on:
      - backend
    networks:
      - services

  backend:
    image: gustavoaborges/ifa-br-backend:latest
    environment:
      SITE: IFABR
      ZEO_ADDRESS: db:8100
    ports:
    - "8080:8080"
    depends_on:
      - db
    networks:
      - services

  db:
    image: plone/plone-zeo:latest
    restart: always
    volumes:
      - data:/data
    ports:
    - "8100:8100"
    networks:
      - services

volumes:
  data: {}

networks:
  services:
    internal: true
  web:
    internal: false #needs to be created by other file
    name: shared-web