version: "3"
services:

  webserver:
    image: nginx
    environment:
      - NGINX_SERVER_NAME
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    image: gustavoaborges/ifa-br-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/IFABR
      ADDONS: "@eeacms/volto-listing-block"
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: gustavoaborges/ifa-br-backend:latest
    environment:
      SITE: IFABR
    volumes:
      - data:/data
    ports:
    - "8080:8080"

volumes:
  data: {}